services:
  omeka:
    env_file:
      - ./.env
    image: nealpowers104/exploreuk-web-app:$EUK_TAG
    networks:
        - app_network
    volumes:
      - omeka_static:/omeka
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pgrep php-fpm || exit 1"]
      interval: 1s
      timeout: 3s
      retries: 30

  findingaid:
    image: nealpowers104/findingaid:$FA_TAG
    volumes:
      - ./xml:/app/xml
    networks:
      - app_network

  web:
    image: nginx:1.29
    networks:
      - app_network
    volumes:
      - ${PWD}/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - omeka_static:/omeka
      - findingaid:/findingaid
    ports:
      - 8080:80
    depends_on:
      omeka:
        condition: service_healthy

  db:
    env_file:
      - ./.env
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
  omeka_static:
  findingaid:
