services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - omeka:/var/www/html:ro
    depends_on:
      - omeka
    networks:
      - app-network

  omeka:
    build:
      context: .
      target: ${APP_ENV}
      args:
        OMEKA_THEME: ${OMEKA_THEME}
    volumes:
      - ./backup:/tmp/backup:ro
      - ./app:/app:rw
      - omeka:/var/www/html
    env_file:
      - ".env"
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./backup/omeuka.sql:/docker-entrypoint-initdb.d/omeuka.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  omeka:

networks:
  app-network:
    driver: bridge
