services:
  omeka:
    env_file:
      - ./.env
    image: nealpowers104/exploreuk-web-app:${EUK_TAG}
    networks:
      - app_network
    volumes:
      - omeka_static:/omeka
    depends_on:
      - db

  findingaid:
    image: nealpowers104/exploreuk-findingaid:${FA_TAG}
    volumes:
      # Change to directory on host
      - ./xml:/app/xml
      - findingaid:/app
    networks:
      - app_network

  web:
    image: nginx:latest
    networks:
      - app_network
    volumes:
      - ${PWD}/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - omeka_static:/var/www/html
      - findingaid:/findingaid
    ports:
      - 8080:80
    depends_on:
      - omeka

  db:
    env_file:
      - ./.env
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
  omeka_static:
  findingaid:
