services:
  exploreuk:
    build:
      context: .
      target: ci
    volumes: !reset []
    env_file:
      - .env.ci
    develop: null

  web:
    env_file:
      - .env.ci
    ports: !reset [] # disable publish ports for jobs
