services:
  omeka:
    build:
      context: .
      target: ci
    volumes: []
    env_file:
      - .env.ci
    develop: null

  web:
    env_file:
      - .env.ci
    ports: [] # disable publish ports for jobs

  findingaid:
    image: nealpowers104/findingaid:latest

  db:
    env_file:
      - .env.ci
