services:
  omeka:
    build:
      context: .
      # This docker-compose is for development purposes
      target: dev
    volumes:
      - ./app:/app
      - omeka_static:/omeka
    env_file:
      - ".env"
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  web:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - omeka_static:/var/www/html:ro
    depends_on:
      - omeka
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      # For loading from backup on first spin-up
      - ./backup/omeuka.sql:/docker-entrypoint-initdb.d/omeuka.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  omeka_static:

networks:
  app-network:
    driver: bridge
