FROM php:8.1-fpm

RUN apt-get update && apt-get install -y \
	imagemagick \
	curl \
	unzip \
	&& apt-get clean

RUN curl -L https://github.com/omeka/Omeka/releases/download/v3.1.2/omeka-3.1.2.zip -o omeka.zip && \
	unzip omeka.zip && \
	cp -r omeka-3.1.2 ./omeka && \
	rm -r omeka-3.1.2 && \
	rm omeka.zip
